### ISSUE TITLE
Boot troubles

### ISSUE THREAD

**Issue by tappmann** [shagu/arch-install#1]
Dear Shagu,
thanks for providing such an great installer :-)
Since I had some boot troubles on my native system I tried the installer within the virtualbox.
I taken settings as follows:
Languange: de
Device: /dev/sda
UEFI: n
Desktop: mate

When I boot into the new installation following happens

Grub selection is available
starting version 238

ERROR: device /dev/mapper/lvm-system not found. Skipping fsck

Then I´m dropped into an emergency shell.

Checking the system with the live iso brings following results: 
/dev/sda1 is marked as boot
/dev/sda2 is setup and contains the following partitions

/dev/mapper/lvm-system   -> can mount and browse
/dev/mapper/lvm-home     -> can mount and browse

Do you have any idea why this happens?

Thx in advance for providing a fix :-)

**Comment by shagu** [comment]
Hi @tappmann,

Thanks for your report, I'm trying to reproduce your issue right now inside of a VirtualBox.
I assume you've been using the following additional settings:
* Reuse existing: No
* Additional Tweaks: None

Is this correct?

**Comment by tappmann** [comment]
Hi @shagu,
thanks for your fast response. Yes, the assumption is correct. This settings i did not use.

**Comment by shagu** [comment]
The installer didn't set the required `CMDLINE` settings, inside the `/etc/default/grub` configuration, which is only used for non-UEFI systems. This is now fixed on the latest revision.

Related Fixes:
https://github.com/shagu/arch-install/commit/bc495fe1c20a9afb8d8457e85cc43d3ec1b34365
https://github.com/shagu/arch-install/commit/713be49fddbd7ef04b006dc6e5f26272e6c98553
