### ISSUE TITLE
Choose partition / disk with more detail

### ISSUE THREAD

**Issue by stevemcqueenz** [shagu/arch-install#2]
Any chance to choose the disk or partition in more detail instead of only /dev/sda I would like to have it more granular /dev/sda3. So it is not breaking the rest of the system running on /dev/sda

**Comment by shagu** [comment]
Hi,

I requires more effort than I'm willing to spend on it, as I wouldn't use it. You'd have to put in additional checks wether you want to install/format the EFI/mbr partition and checks to keep pre-installed OS entries. It also would need more advanced partitioning options. After having a quick look, this opens alot of corner cases that need to be handled properly aswell.

So the short answer is "No" from my side. 
If you're willing to work on that, feel free to reopen and send a PR :)
